use_frameworks!

platform :ios, '9.0'

target 'ConsoliAds-SDK_Example' do
  pod 'ConsoliAds-SDK', :path => '../'

  target 'ConsoliAds-SDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
